# Generated by Django 4.2.2 on 2023-07-01 04:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('name', models.TextField()),
                ('wtype', models.TextField()),
                ('region', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=140)),
                ('name', models.TextField(blank=True, max_length=32)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whisky.tastingnote')),
            ],
        ),
    ]
