# Generated by Django 4.2.2 on 2023-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='tag',
            field=models.TextField(blank=True),
        ),
    ]
